### ISSUE TITLE
What version of yarn to use?

### ISSUE THREAD

**Issue by job** [dashcare/irrexplorer#72]
What version of yarn is recommended?

This is Ubuntu 20.04

```
(venv) irrexplorer2@irrexplorer0:~/irrexplorer$ yarn --version
0.32+git
(venv) irrexplorer2@irrexplorer0:~/irrexplorer$ poetry run frontend-install
Usage: yarn [options]

yarn: error: no such option: --cwd
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/irrexplorer2/irrexplorer/scripts.py", line 28, in frontend_install
    check_call(["yarn", "--cwd", "frontend/"])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['yarn', '--cwd', 'frontend/']' returned non-zero exit status 2.

```

**Comment by mxsasha** [comment]
I have tested with 1.22.10 on Mac OS and Arch. So yours seems really old. From some googling, it seems like the typical thing is to install yarn not through apt, but through npm, as `npm install -g yarn`.
